In [1]:
import pandas as pd
y_test = [1,2,3,4]
pd.get_dummies(y_test, drop_first=False).values

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=uint8)

In [1]:
for i in range(0,40,4):
    print(i*4,(i+1)*4)

0 4
16 20
32 36
48 52
64 68
80 84
96 100
112 116
128 132
144 148


In [6]:
import numpy as np
a = np.random.rand(3,4)
a

array([[0.84056993, 0.83078629, 0.59954641, 0.04083566],
       [0.64287425, 0.51416778, 0.16983487, 0.42643008],
       [0.03247375, 0.67064007, 0.18758156, 0.21731858]])

In [7]:
a[a[:,3]>.2,0]=0
a

array([[0.84056993, 0.83078629, 0.59954641, 0.04083566],
       [0.        , 0.51416778, 0.16983487, 0.42643008],
       [0.        , 0.67064007, 0.18758156, 0.21731858]])

In [9]:
#np.log(x)=0.0000000001
np.exp(0.0000000001)

1.0000000001

In [10]:
np.log(1)

0.0

In [25]:
np.geomspace(0.01,1,10).round(3) 

array([0.01 , 0.017, 0.028, 0.046, 0.077, 0.129, 0.215, 0.359, 0.599,
       1.   ])

In [ ]:
n